# Generated by Django 2.1.7 on 2019-03-04 23:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('post', '0003_post_invite'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='post',
            name='invite',
        ),
    ]
