# Generated by Django 2.1.7 on 2019-03-05 00:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('post', '0004_remove_post_invite'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='invite',
            field=models.CharField(blank=True, max_length=20),
        ),
    ]
